### ISSUE TITLE
hcaptcha trouble

### ISSUE THREAD

**Issue by chemax** [pguardiario/captchas#1] opened 2020-08-12 04:26 UTC
For debug, i was trying load script manually in firefox

`var scriptElement=document.createElement('script');`
`scriptElement.type = 'text/javascript';`
`scriptElement.src = "https://cdn.jsdelivr.net/gh/pguardiario/captchas/captchas.js";`
`document.head.appendChild(scriptElement);`

and solve

```solve(["my_ip_key", {}], (...x) => {console.log(x)})```
  
And result https://i.imgur.com/oWjPdtQ.png

```solve(["542cc7c43c0cf1263e539a2bf99c37c2", {}], (...x) => {console.log(x)})
hcaptcha captchas.js:70:13
Uncaught (in promise) TypeError: document.querySelector(...) is null
    solveHcaptcha https://cdn.jsdelivr.net/gh/pguardiario/captchas/captchas.js:71
    solveCaptchas https://cdn.jsdelivr.net/gh/pguardiario/captchas/captchas.js:97
    solve https://cdn.jsdelivr.net/gh/pguardiario/captchas/captchas.js:109
    <anonymous> debugger eval code:1
captchas.js:71:28
    solve https://cdn.jsdelivr.net/gh/pguardiario/captchas/captchas.js:109
    AsyncFunctionThrow self-hosted:688
    (Асинхронный: async)
    <анонимный> debugger eval code:1
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:244
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:168
    evaluateJS resource://devtools/server/actors/webconsole.js:1139
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:1033
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
Promise { "pending" }
​
<state>: "pending"
​
<prototype>: PromiseProto { … }```  

What can i do with it?

**Comment by pguardiario** [comment] 2020-08-12 06:05
That means it can't find the sitekey. Can you post the url?

**Comment by chemax** [comment] 2020-08-12 07:10
https://tmonh.com/50r
But it work only with public proxy, BEFORE load site. Not on site.

**Comment by pguardiario** [comment] 2020-08-12 08:22
Sorry, I don't have enough to troubleshoot this. I don't understand your last message and I don't see a hcaptcha on that page.

**Comment by chemax** [comment] 2020-08-12 08:25
When you use a public proxy, cloudflare use hCaptcha to protect site from bot or ddos. 
Try use public proxy (like this 217.163.11.223:8080) and you will see.

**Comment by pguardiario** [comment] 2020-08-13 01:19
Ok, please do me a favor and paste the smallest amount of code that reproduces the issue

**Comment by chemax** [comment] 2020-08-13 03:45
```var scriptElement=document.createElement('script');
scriptElement.type = 'text/javascript';
scriptElement.src = "https://cdn.jsdelivr.net/gh/pguardiario/captchas/captchas.js";
document.head.appendChild(scriptElement);```

**Comment by pguardiario** [comment] 2020-08-13 05:34
I'm looking for a short puppeteer or python / selenium script that reproduces the issue.

**Comment by chemax** [comment] 2020-08-13 05:37
It exactly what puppeteer does there: 
`await page.addScriptTag({url: "https://cdn.jsdelivr.net/gh/pguardiario/captchas/captchas.js"})`
`    let status = await page.evaluate(async () => {`
`        return new Promise((resolve, reject) => {`
`            solve(["token", {}, resolve])`
`        })`
`    })`
You can see it there https://gist.github.com/chemax/3269e8ff9cae1758ecf8b7fd4927a63e

**Comment by pguardiario** [comment] 2020-08-13 06:02
Sorry but that proxy isn't working for me. I'm going to close this one because I can't help you.

**Closed by pguardiario** 2020-08-13 06:02 UTC
